/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate the configured administrator */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh cookie and issue a new access token */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh family and clear its cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated administrator */
        get: operations["getCurrentAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/colaboradores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List collaborators; archived status requires authentication */
        get: operations["listColaboradores"];
        put?: never;
        /** Create a collaborator */
        post: operations["createColaborador"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/colaboradores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get a collaborator; archived records appear only to administrators */
        get: operations["getColaborador"];
        /** Update a collaborator */
        put: operations["updateColaborador"];
        post?: never;
        /** Archive a collaborator without deleting attendance */
        delete: operations["archiveColaborador"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/colaboradores/{id}/restaurar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an archived collaborator */
        post: operations["restoreColaborador"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workshops; archived status requires authentication */
        get: operations["listWorkshops"];
        put?: never;
        /** Create a workshop, optionally linking an archived predecessor */
        post: operations["createWorkshop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get workshop details and active participants */
        get: operations["getWorkshop"];
        /** Update workshop metadata */
        put: operations["updateWorkshop"];
        post?: never;
        /** Archive a workshop and create an archive event */
        delete: operations["archiveWorkshop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{id}/restaurar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a workshop when its quarter is available */
        post: operations["restoreWorkshop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{id}/participantes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the complete attendance list */
        put: operations["replaceParticipantes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{id}/participantes/{colaboradorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                colaboradorId: components["parameters"]["ColaboradorId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Idempotently add one participant */
        put: operations["addParticipante"];
        post?: never;
        /** Idempotently remove one participant */
        delete: operations["removeParticipante"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        AuthResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            admin: components["schemas"]["AdminSummary"];
        };
        AdminSummary: {
            id: string;
            username: string;
        };
        ColaboradorInput: {
            nome: string;
        };
        Colaborador: {
            id: number;
            nome: string;
            status: components["schemas"]["RecordStatus"];
            /** Format: date-time */
            archivedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkshopInput: {
            nome: string;
            /**
             * Format: date-time
             * @description Thursday at 16:00 in America/Recife, with explicit offset
             */
            dataRealizacao: string;
            descricao: string;
        };
        CreateWorkshopRequest: components["schemas"]["WorkshopInput"] & {
            /** @description Active collaborators initially associated with the workshop */
            colaboradorIds?: number[];
            substituiWorkshopId?: number | null;
        };
        WorkshopSummary: {
            id: number;
            nome: string;
            /** Format: date-time */
            dataRealizacao: string;
            /** Format: date-time */
            dataTermino: string;
            descricao: string;
            status: components["schemas"]["RecordStatus"];
            /** Format: date-time */
            archivedAt?: string | null;
            participantCount: number;
        };
        WorkshopDetail: components["schemas"]["WorkshopSummary"] & {
            participantes: components["schemas"]["Colaborador"][];
            /** @description Empty for public callers; populated for administrators */
            archiveEvents: components["schemas"]["WorkshopArchiveEvent"][];
        };
        WorkshopArchiveEvent: {
            id: number;
            reason: components["schemas"]["ArchiveReason"];
            /** Format: date-time */
            archivedAt: string;
            archivedByAdminId: string;
            /** Format: date-time */
            restoredAt?: string | null;
            replacementWorkshopId?: number | null;
        };
        ArchiveWorkshopRequest: {
            reason: components["schemas"]["ArchiveReason"];
        };
        ReplaceParticipantesRequest: {
            colaboradorIds: number[];
        };
        PagedColaboradores: {
            items: components["schemas"]["Colaborador"][];
            totalItems: number;
            offset: number;
            limit: number;
        };
        PagedWorkshops: {
            items: components["schemas"]["WorkshopSummary"][];
            totalItems: number;
            offset: number;
            limit: number;
        };
        /** @enum {string} */
        RecordStatus: "active" | "archived";
        /** @enum {string} */
        ArchiveReason: "manual" | "replacement";
        ProblemDetails: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            code: string;
            traceId?: string;
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Request validation failed */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentication is absent or invalid */
        UnauthorizedProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Origin or authorization policy rejected the operation */
        ForbiddenProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist or is not visible to the caller */
        NotFoundProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Domain state conflicts with the requested change */
        ConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        Id: number;
        ColaboradorId: number;
        Query: string;
        Offset: number;
        Limit: number;
        /** @description Archived and all views require administrator authentication */
        Status: "active" | "archived" | "all";
        OriginHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; also sets the HttpOnly refresh cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["OriginHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session refreshed and cookie rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["OriginHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended; idempotent when no active session remains */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ForbiddenProblem"];
        };
    };
    getCurrentAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current administrator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSummary"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
        };
    };
    listColaboradores: {
        parameters: {
            query?: {
                query?: components["parameters"]["Query"];
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
                /** @description Archived and all views require administrator authentication */
                status?: components["parameters"]["Status"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collaborators ordered by name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedColaboradores"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
        };
    };
    createColaborador: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColaboradorInput"];
            };
        };
        responses: {
            /** @description Collaborator created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Colaborador"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
        };
    };
    getColaborador: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collaborator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Colaborador"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    updateColaborador: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColaboradorInput"];
            };
        };
        responses: {
            /** @description Collaborator updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Colaborador"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    archiveColaborador: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived; idempotent when already archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    restoreColaborador: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collaborator restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Colaborador"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    listWorkshops: {
        parameters: {
            query?: {
                query?: components["parameters"]["Query"];
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
                /** @description Archived and all views require administrator authentication */
                status?: components["parameters"]["Status"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workshops ordered by date descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedWorkshops"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
        };
    };
    createWorkshop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkshopRequest"];
            };
        };
        responses: {
            /** @description Workshop created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDetail"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            409: components["responses"]["ConflictProblem"];
        };
    };
    getWorkshop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workshop details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDetail"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    updateWorkshop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkshopInput"];
            };
        };
        responses: {
            /** @description Workshop updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDetail"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
        };
    };
    archiveWorkshop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveWorkshopRequest"];
            };
        };
        responses: {
            /** @description Workshop archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    restoreWorkshop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workshop restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDetail"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
        };
    };
    replaceParticipantes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceParticipantesRequest"];
            };
        };
        responses: {
            /** @description Updated workshop details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDetail"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
        };
    };
    addParticipante: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                colaboradorId: components["parameters"]["ColaboradorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant present */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
        };
    };
    removeParticipante: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                colaboradorId: components["parameters"]["ColaboradorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
}
