<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="MySql.EntityFrameworkCore" />
    <ProjectReference Include="../WorkshopTracker.Application/WorkshopTracker.Application.csproj" />
    <ProjectReference Include="../WorkshopTracker.Domain/WorkshopTracker.Domain.csproj" />
  </ItemGroup>

</Project>
